name: 自动构建Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            git \
            wget

      - name: 安装Buildozer和依赖
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython pillow

      - name: 配置Java 11环境（关键）
        uses: actions/setup-java@v4  # 使用官方Action自动配置Java
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 手动配置Android SDK
        run: |
          # 1. 配置SDK路径并创建目录
          export ANDROID_SDK_ROOT="/home/runner/.buildozer/android/platform/android-sdk"
          mkdir -p $ANDROID_SDK_ROOT
          sudo chmod -R 777 $ANDROID_SDK_ROOT
          
          # 2. 下载可用的cmdline-tools（10406996版本，兼容镜像）
          CMDLINE_VERSION="10406996"
          CMDLINE_ZIP="commandlinetools-linux-${CMDLINE_VERSION}_latest.zip"
          if ! wget "https://mirrors.tuna.tsinghua.edu.cn/android/repository/$CMDLINE_ZIP" -O cmdline-tools.zip; then
            wget "https://dl.google.com/android/repository/$CMDLINE_ZIP" -O cmdline-tools.zip
          fi
          
          # 3. 解压并整理cmdline-tools目录结构
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-tmp
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools-tmp/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          
          # 4. 配置SDK工具路径
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --licenses
          
          # 5. 安装Build Tools和必要组件
          sdkmanager \
            "build-tools;31.0.0" \
            "platform-tools" \
            "platforms;android-31" \
            "tools"  # 保留旧版tools，兼容Buildozer调用
          
          # 6. 验证安装结果
          echo "Build Tools目录："
          ls -la $ANDROID_SDK_ROOT/build-tools/
          echo "aidl路径："
          ls -la $ANDROID_SDK_ROOT/build-tools/31.0.0/aidl || echo "aidl未找到"

      - name: 构建APK（强制使用Java 11）
        run: |
          export ANDROID_SDK_ROOT="/home/runner/.buildozer/android/platform/android-sdk"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          buildozer android debug -v  # -v参数显示详细日志
        env:
          ANDROID_SDK_ROOT: "/home/runner/.buildozer/android/platform/android-sdk"
          ANDROID_NDK_URL: "https://mirrors.tuna.tsinghua.edu.cn/android/ndk/android-ndk-r25b-linux.zip"  # NDK用清华镜像加速

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: 屏幕调整工具APK
          path: bin/*.apk
