name: 自动构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ANDROID_SDK_ROOT: "/home/runner/.buildozer/android/platform/android-sdk"
      ANDROID_NDK_VERSION: "25b"
      CMDLINE_VERSION: "9477386"
      ANDROID_ACCEPT_SDK_LICENSES: "yes"

    steps:
      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 2. 安装Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.18'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
            .github/workflows/*.yml

      - name: 3. 安装系统依赖+证书更新
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            openjdk-11-jdk \
            unzip \
            wget \
            ca-certificates \
            libssl-dev
          sudo update-ca-certificates
          java -version
          javac -version

      - name: 4. 安装Buildozer与依赖
        run: |
          python -m pip install --upgrade pip==25.2
          pip install \
            buildozer==1.5.0 \
            cython==3.1.3 \
            pillow==11.3.0 \
            pexpect==4.9.0 \
            sh==1.14.3
          buildozer --version
          cython --version

      - name: 5. 配置Java 11环境
        uses: actions/setup-java@v4
        with:
          java-version: '11.0.28'
          distribution: 'temurin'
          java-package: 'jdk'
        env:
          JAVA_HOME: "/usr/lib/jvm/temurin-11-jdk-amd64"

      - name: 6. 下载并配置Android SDK（修复jar名称）
        run: |
          # 创建目录并授权
          mkdir -p $ANDROID_SDK_ROOT
          sudo chmod -R 777 $ANDROID_SDK_ROOT
          echo "SDK路径：$ANDROID_SDK_ROOT"

          # 下载cmdline-tools
          CMDLINE_ZIP="commandlinetools-linux-${CMDLINE_VERSION}_latest.zip"
          MIRRORS=(
            "https://mirrors.ustc.edu.cn/android/repository/"
            "https://mirrors.aliyun.com/android/repository/"
            "https://dl.google.com/android/repository/"
          )
          for MIRROR in "${MIRRORS[@]}"; do
            echo "尝试从镜像下载：$MIRROR$CMDLINE_ZIP"
            if wget --no-check-certificate -O cmdline-tools.zip "$MIRROR$CMDLINE_ZIP"; then
              echo "从$MIRROR下载成功！"
              break
            fi
          done

          # 解压并修正目录结构
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/tools
          rm -f cmdline-tools.zip

          # 配置环境变量
          export PATH="$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          export JAVA_HOME="/usr/lib/jvm/temurin-11-jdk-amd64"

          # 关键修复：使用实际存在的sdkmanager-classpath.jar
          SDK_JAR_PATH="$ANDROID_SDK_ROOT/tools/lib/sdkmanager-classpath.jar"
          if [ ! -f "$SDK_JAR_PATH" ]; then
            echo "错误：未找到$sdkmanager-classpath.jar，路径：$SDK_JAR_PATH"
            ls -la $ANDROID_SDK_ROOT/tools/lib/
            exit 1
          fi
          echo "找到sdkmanager-classpath.jar：$SDK_JAR_PATH"

          # 安装SDK组件（使用正确的jar包）
          echo "安装SDK组件..."
          java --add-modules java.xml.bind -jar "$SDK_JAR_PATH" \
            "platform-tools" \
            "build-tools;31.0.0" \
            "platforms;android-31" \
            "tools"

          # 验证安装结果
          echo "=== SDK安装验证 ==="
          if [ -d "$ANDROID_SDK_ROOT/build-tools/31.0.0" ]; then
            echo "Build Tools 31.0.0 安装成功"
          else
            echo "错误：Build Tools 31.0.0 未安装"
            ls -la $ANDROID_SDK_ROOT/build-tools/
            exit 1
          fi
          if [ -f "$ANDROID_SDK_ROOT/build-tools/31.0.0/aidl" ]; then
            echo "aidl工具找到"
          else
            echo "错误：aidl工具缺失"
            exit 1
          fi

      - name: 7. 构建APK（详细日志）
        run: |
          export JAVA_HOME="/usr/lib/jvm/temurin-11-jdk-amd64"
          export PATH="$JAVA_HOME/bin:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
          export ANDROID_NDK_URL="https://mirrors.tuna.tsinghua.edu.cn/android/ndk/android-ndk-r${ANDROID_NDK_VERSION}-linux.zip"
          
          buildozer android debug --log-level 2 \
            --android-sdk "$ANDROID_SDK_ROOT" \
            --android-ndk "$ANDROID_SDK_ROOT/../android-ndk-r${ANDROID_NDK_VERSION}"

      - name: 8. 上传产物（含日志）
        uses: actions/upload-artifact@v4
        with:
          name: 屏幕调整工具APK（含日志）
          path: |
            bin/*.apk
            .buildozer/logs/*.log
          retention-days: 14
        if: always()
