name: 自动构建Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            git \
            wget

      - name: 安装Buildozer和依赖
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython pillow

      - name: 手动配置Android SDK（修复cmdline-tools下载）
        run: |
          # 明确SDK路径
          export ANDROID_SDK_ROOT="/home/runner/.buildozer/android/platform/android-sdk"
          mkdir -p $ANDROID_SDK_ROOT
          sudo chmod -R 777 $ANDROID_SDK_ROOT
          
          # 更换为镜像中存在的cmdline-tools版本（10406996是稳定版）
          CMDLINE_VERSION="10406996"
          CMDLINE_ZIP="commandlinetools-linux-${CMDLINE_VERSION}_latest.zip"
          
          # 先尝试清华镜像，失败则用官方源
          if ! wget "https://mirrors.tuna.tsinghua.edu.cn/android/repository/$CMDLINE_ZIP" -O cmdline-tools.zip; then
            echo "清华镜像下载失败，尝试官方源..."
            wget "https://dl.google.com/android/repository/$CMDLINE_ZIP" -O cmdline-tools.zip
          fi
          
          # 解压并整理目录结构
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-tmp
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools-tmp/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          
          # 配置环境变量
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          
          # 接受许可证并安装组件
          yes | sdkmanager --licenses
          sdkmanager \
            "build-tools;31.0.0" \
            "platform-tools" \
            "platforms;android-31" \
            "tools"
          
          # 验证安装
          echo "Build Tools目录内容："
          ls -la $ANDROID_SDK_ROOT/build-tools/
          echo "aidl是否存在："
          ls -la $ANDROID_SDK_ROOT/build-tools/31.0.0/aidl || echo "警告：aidl未找到"

      - name: 构建APK
        run: |
          export ANDROID_SDK_ROOT="/home/runner/.buildozer/android/platform/android-sdk"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: "/home/runner/.buildozer/android/platform/android-sdk"

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: 屏幕调整工具APK
          path: bin/*.apk
