name: 自动构建Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            git

      - name: 安装Buildozer和依赖
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython pillow

      - name: 初始化Buildozer环境
        run: |
          # 先让Buildozer创建必要的目录结构
          buildozer android debug --dry-run
          
          # 明确设置SDK路径变量
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          
          # 确保sdkmanager可执行
          chmod +x $ANDROID_SDK_ROOT/tools/bin/sdkmanager
          
          # 强制接受所有许可证（关键步骤）
          echo "y" | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses
          
          # 手动安装指定版本的Build Tools（使用稳定版31.0.0）
          echo "y" | $ANDROID_SDK_ROOT/tools/bin/sdkmanager \
            "build-tools;31.0.0" \
            "platform-tools" \
            "platforms;android-31"

      - name: 构建APK
        run: |
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
          buildozer android debug
        env:
          ANDROID_SDK_URL: https://mirrors.tuna.tsinghua.edu.cn/android/sdk/
          ANDROID_NDK_URL: https://mirrors.tuna.tsinghua.edu.cn/android/ndk/

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: 屏幕调整工具APK
          path: bin/*.apk
